### ISSUE TITLE
Create a Wiki Page on how the Link Repository Works

### ISSUE THREAD

**Issue by azenla** [IOT-DSA/links#2]
We have many different DSLink authors. It has become very clear that we need clear documentation on how the Link Repository works, and how to add a DSLink.

**Comment by Pacane** [comment]
@kaendfinger this would be very important, because you're bottleneck here. Maybe explain to me, and so I can document it.

**Comment by Pacane** [comment]
Done https://github.com/IOT-DSA/links/wiki
